import { Media } from "./Media";

export interface Post {
    approved_at_utc: null | string;
    subreddit: string;
    selftext: string;
    author_fullname: string;
    saved: boolean;
    mod_reason_title: null | string;
    gilded: number;
    clicked: boolean;
    title: string;
    link_flair_richtext: Array<{
        e: string;
        a?: string;
        t?: string;
        u?: string;
    }>;
    subreddit_name_prefixed: string;
    hidden: boolean;
    pwls: number;
    link_flair_css_class: string;
    downs: number;
    thumbnail_height: null | number;
    top_awarded_type: null | string;
    hide_score: boolean;
    name: string;
    quarantine: boolean;
    link_flair_text_color: string;
    upvote_ratio: number;
    author_flair_background_color: string;
    subreddit_type: string;
    ups: number;
    total_awards_received: number;
    media_embed: {};
    thumbnail_width: null | number;
    author_flair_template_id: string;
    is_original_content: boolean;
    user_reports: any[];
    secure_media: null | any;
    is_reddit_media_domain: boolean;
    is_meta: boolean;
    category: null | string;
    secure_media_embed: {};
    link_flair_text: string;
    can_mod_post: boolean;
    score: number;
    approved_by: null | string;
    is_created_from_ads_ui: boolean;
    author_premium: boolean;
    thumbnail: string;
    edited: boolean;
    author_flair_css_class: null | string;
    author_flair_richtext: Array<{
        a?: string;
        e: string;
        t?: string;
        u?: string;
    }>;
    gildings: {};
    content_categories: null | any;
    is_self: boolean;
    mod_note: null | string;
    created: number;
    link_flair_type: string;
    wls: number;
    removed_by_category: null | string;
    banned_by: null | string;
    author_flair_type: string;
    domain: string;
    allow_live_comments: boolean;
    selftext_html: string;
    likes: null | number;
    suggested_sort: string;
    banned_at_utc: null | string;
    view_count: null | number;
    archived: boolean;
    no_follow: boolean;
    is_crosspostable: boolean;
    pinned: boolean;
    over_18: boolean;
    all_awardings: Award[];
    awarders: string[];
    media_only: boolean;
    link_flair_template_id: string;
    can_gild: boolean;
    spoiler: boolean;
    locked: boolean;
    author_flair_text: string;
    treatment_tags: string[];
    visited: boolean;
    removed_by: null | string;
    num_reports: null | number;
    distinguished: null | string;
    subreddit_id: string;
    author_is_blocked: boolean;
    mod_reason_by: null | string;
    removal_reason: null | string;
    link_flair_background_color: string;
    id: string;
    is_robot_indexable: boolean;
    report_reasons: string[];
    author: string;
    discussion_type: null | string;
    num_comments: number;
    send_replies: boolean;
    whitelist_status: string;
    contest_mode: boolean;
    mod_reports: string[];
    author_patreon_flair: boolean;
    author_flair_text_color: string;
    permalink: string;
    parent_whitelist_status: string;
    stickied: boolean;
    url: string;
    subreddit_subscribers: number;
    created_utc: number;
    num_crossposts: number;
    media: null | Media;
    is_video: boolean;
}